# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYOIldLxau6bY2bOiWlhWWapMI3TiaxJ
"""

import pandas as pd
guruh= pd.DataFrame({
    'Ism':[ 'Zikrullo', 'Dilyorbek', 'Bekzodbek', 'Bekmurod', 'Azizbek', 'Behruzbek', 'Muhammadali', 'Husniddin', 'Muhammaddiyor', 'Shoxruh'      ],
    'Familiya':[ 'Maxsudov', 'Yusupov', 'Murodjonov', 'Mahmudov', 'Muhammadov', 'Yunusaliyev', 'Abdusalimov', 'Rahmatov', 'Nuriddinov', "G'ofurjonov"     ],
    'Telefon raqami':[ '956651255','936657743', '945738221', '972234123', '884636231', '884635221', '505005535', '505566557', '773453221', '945566677'      ],
    'Yashash manzili':[ "Dang'ara tumani", "O'zbekiston tumani", "Beshariq tumani", 'Andijon viloyati', "Beshariq tumani", "Beshariq tumani", "FArg'ona viloyati", "Beshariq tumani", 'Oltiariq tumani', 'Namangan viloyati'      ]

})
print(guruh)

guruh.to_excel('guruh.xlsx')

guruh